In [1]:
#Handon questions on numpy


In [3]:
#Create numpy array with datatype int and float
import numpy as np

In [4]:
arr1= np.array([1,2,3,4,5,6,7,8,9,0],dtype=int)

In [5]:
arr1

array([1, 2, 3, 4, 5, 6, 7, 8, 9, 0])

In [6]:
arr1.dtype

dtype('int32')

In [16]:
arr2= np.array([1,2,3,4,5,6,7.2,8,9,0], dtype=float)

In [17]:
arr2

array([1. , 2. , 3. , 4. , 5. , 6. , 7.2, 8. , 9. , 0. ])

In [18]:
arr0d = np.array(10)

In [19]:
arr1d = np.array([2,34,5,34,2])

In [20]:
arr2d= np.array(
    [[1,2],[3,4]]
)

In [21]:
arr3d= np.array(
    [
        [[1,2],[3,4]],
        [[5,6],[7,8]]
    ]
)

In [22]:
arr2.shape

(10,)

In [23]:
arr1.shape

(10,)

In [24]:
arr2.ndim

1

In [25]:
arr1.ndim

1

In [26]:
arr0d.shape

()

In [27]:
arr1d.shape

(5,)

In [28]:
arr2d.shape

(2, 2)

In [29]:
arr3d.shape

(2, 2, 2)

In [37]:
#shape of array should be 2x5 and all elements should be zero
zero = np.array((2,5))
np.zeros(zero)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [38]:
#all elementes should be 5

In [43]:
arr5= np.full((2,5),5)

In [44]:
arr5

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [50]:
#numpy array with random int in range 0-100 and sample size should be 25
a = np.random.randint(1,101, size=25)
a

array([32, 97, 84,  7, 31, 14, 47, 49, 66, 82, 27, 87, 61, 41, 36, 41, 68,
       40,  1, 90, 19, 60, 97, 85, 95])

In [51]:
a.dtype

dtype('int32')

In [52]:
print(a)

[32 97 84  7 31 14 47 49 66 82 27 87 61 41 36 41 68 40  1 90 19 60 97 85
 95]


In [59]:
#create a 2x3 matrix with random values and update the shape of the array
b= np.random.randint(1,101, size=(2,3))

In [60]:
b

array([[33, 34, 36],
       [45, 19, 78]])

In [63]:
c = np.reshape(b,(3,2))

In [64]:
c

array([[33, 34],
       [36, 45],
       [19, 78]])

In [69]:
#numpy array square matrix of 3 with all element 1
arr100 = np.ones((3,3), dtype=int)

In [70]:
arr100

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])