In [1]:
#we will learn about numpy
import numpy as np

In [3]:
#Numpy -> Num is numericals and py is python means NUmerical Python
#We use to do it numerical operations 
#Numpy there is one prior topic only which is array

In [4]:
#array is where i can store multiple data but in same datatype only- if int then all data is in int only!

In [5]:
#We have lists in python , then why we are not using list? list can store multiple data in multiple  datatype

#disadvantages of list 
#In list - It takes alot of space and take alot of time in execution!
#HENCE 

In [6]:
#Numpy introduces Array - It is fast execution and consuming less space as well

In [7]:
#Numpy module/ libraries created by using C/C++

In [8]:
#computation is faster because of it - cause compiler is used instead of interpreter  (python's translator)

In [13]:
arr = np.array([1,2,3,4])
print(arr) #similar like list but it is a array

[1 2 3 4]


In [15]:
type(arr)

numpy.ndarray

In [16]:
#ndarray means n dimensions array ( means the array have n dimensions)

In [19]:
arr2 = np.array([1,2,43,'meow'])
#it should give us error but it dont - cause it is very powerful library and it handles the errors!
print(arr2)

['1' '2' '43' 'meow']


In [20]:
#it converted 1,2,3 as string like 'meow' - changed datatype to all int

In [21]:
#int<float<string - followed by numpy! 

In [25]:
#lets create zero dimension array --> 0 Dimension means Scaler Value (like a point)
arr4 = np.array(20)
arr4

array(20)

In [28]:
arr4.ndim

0

In [31]:
#Hence proven that the arr4 is zero dimension 
arr4.shape

()

In [34]:
#creating 1 dimension array
arr5 = np.array([1,2,3,4,5,6])
arr5.shape

(6,)

In [35]:
#shape giving 6 rows zero columns means 1 dimension only

In [37]:
arr5.ndim

1

In [40]:
#creating 2D array
arr6 = np.array([[1,2,3,4],[6,7,8,9]])
arr6


array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [42]:
print(arr6)

[[1 2 3 4]
 [6 7 8 9]]


In [44]:
arr6.ndim

2

In [45]:
arr6.shape

(2, 4)

In [47]:
#means 2 rows and 4 columns or (number of 1d array, number of 0d array inside 1d)

In [48]:
#(number of 1d array, number of elements inside one 1d array) <-- official shape , wont give you confusion in many dimensions 

In [49]:
arr7 = np.array([
    [[1,2,3],[4,5,6]],
    [[7,8,9],[10,11,12]]
])

In [50]:
print(arr7)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [51]:
arr7.ndim

3

In [52]:
arr7.shape

(2, 2, 3)

In [53]:
#( number of 2d array , number of 1d array in 2d, number of elelments in 0d array in 1d)

In [54]:
#INDEXING - when ever you wan to find the position

In [55]:
#for indexing we'll do same for high order array nth array
#  ((nth-1)array element find ), ((nth-2) array element and find), ....)
print(arr7)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [57]:
#if we want to find 9 suppose 
arr7[(1,0,2)] #( 2nd - 2d array, first 1d array of 2d array, 3rd 0d array)

9

In [58]:
#Slicing

In [60]:
arr5

array([1, 2, 3, 4, 5, 6])

In [62]:
#we need value only from 1 to 3
arr5[0:3]

array([1, 2, 3])

In [64]:
#for slicing in 2d
arr6
#i want 2 , 3 as answer

array([[1, 2, 3, 4],
       [6, 7, 8, 9]])

In [73]:
arr6[0 , 1:3] #(1d aray position , slicing of 0d)

array([2, 3])

In [75]:
# i need 1 2 and 6 7 as well
arr6[0:2,0:2]

array([[1, 2],
       [6, 7]])

In [80]:
# i need 3 4 and 8 9 
arr6[0:2, 2:4]

array([[3, 4],
       [8, 9]])

In [72]:
print(arr7)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [81]:
#3D
print(arr7)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [82]:
#i need 2,3 and 8,9
arr7[0:2,0,1:3]

array([[2, 3],
       [8, 9]])

In [85]:
#we want 1 2 4 5 7 8 10 11
arr7[0:2,0:2,0:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[ 7,  8],
        [10, 11]]])

In [92]:
#RESHAPE
arr8 = np.array([1,2,3,4,5,6])

In [93]:
arr8

array([1, 2, 3, 4, 5, 6])

In [94]:
arr8.shape

(6,)

In [98]:
arr8.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [99]:
#reshape done (we just have to take the lcm like here total 6 values so (3,2)and (2,3) is possible)
#for six element 3d array is not possible cause only 2 multiple in lcm

In [101]:
#np.zeros() -> create a numpy array with all the elements zero
arr9 = np.zeros((3,3))

In [102]:
arr9

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [105]:
arr9.dtype

dtype('float64')

In [106]:
arr9 = np.zeros((3,3), dtype='int')

In [107]:
arr9

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [108]:
arr9.dtype

dtype('int32')

In [109]:
#np.ones = create a numpy array with all the element values 1
arr10 = np.ones((3,3), dtype='int')

In [110]:
arr10

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [115]:
#np.full = creates a numpy array with all the elements of desired value
arr11= np.full((3,3),100,dtype='float')

In [116]:
arr11

array([[100., 100., 100.],
       [100., 100., 100.],
       [100., 100., 100.]])

In [121]:
#np.identity = diagonal matrix will become one and all other elements are zero-its determinent is one itself.
arr12 = np.identity(3, dtype=int)
#identity matrix is square always

In [122]:
arr12

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [123]:
#np.eye() - helps us to create rectangular identity matrix
arr13= np.eye(3)

In [124]:
arr13

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [127]:
arr14= np.eye(3,9)

In [128]:
arr14

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.]])

In [137]:
#random is a module is numpy
# np.random.randint()
#rand  and int means random integer -->

x = np.random.randint(1,100) # will give from 1--> 99 any!

In [138]:
x

49

In [139]:
#it alwayes gives new number if you rerun it !

In [146]:
#if we need more than 1 values then
y = np.random.randint(1, 100, size = 1000) #1000 random numbers!

In [147]:
y

array([90, 46, 59, 65, 26, 34, 36, 61, 52, 19,  6, 39,  6, 65, 46, 90, 98,
       57, 32, 16, 32, 31, 84, 25, 57, 93, 91, 13, 24, 84, 55, 36, 27, 82,
       68, 79, 35, 25, 10, 93, 14, 24, 33, 13, 73, 56, 20,  6, 36,  8, 84,
       54, 78, 99, 36, 28, 10, 88, 40, 63, 80, 96, 60, 85, 92, 48, 60, 68,
       82, 98, 63,  1, 60, 47, 83, 55, 15, 98, 95,  6, 70, 68, 96, 84, 78,
       95, 21,  2, 88, 83, 15, 56, 33, 97, 86, 25, 75,  8,  4, 18, 62, 99,
       19, 72, 69, 82, 36, 33, 72, 93, 82, 59, 81, 85,  3, 12, 41, 88, 84,
       10, 22, 32, 39, 42, 27, 72, 14, 43, 44, 68, 44, 70, 75, 91, 77, 30,
       58, 89,  9, 27, 28, 65, 79, 12, 76, 75, 81, 79, 93, 94, 49, 17, 77,
       93, 35, 71, 53, 96, 78, 59, 68, 93, 87, 72, 61, 67, 66,  6, 24, 97,
       65, 72, 38, 84,  1, 35, 83, 32, 54, 84,  1, 64, 77, 66, 96, 40, 47,
       81, 30, 14,  6, 68,  4, 39,  4, 59,  5, 52, 36, 45, 33, 84, 70, 82,
       99, 91, 39, 98,  9, 82, 32, 49, 33, 44, 82, 97, 68, 81, 97, 39, 59,
       91, 89, 93, 94, 76

In [154]:
#Working of choice
dice = [1,2,3,4,5,6]
ludo = np.random.choice(dice)

In [156]:
ludo

5

In [157]:
list1=[1,2,3,4]
list2=[6,7,8,9]
print(list1+list2)

[1, 2, 3, 4, 6, 7, 8, 9]


In [160]:
arr20= np.array([1,2,3,4])

In [165]:
arr21= np.array([5,6,7,8])
print(arr20+arr21)
print(arr20-arr21)

[ 6  8 10 12]
[-4 -4 -4 -4]


In [166]:
#Hence arrays can perform arithematic operations but the list can't they will concatinate!

In [167]:
#hence numpy is for calculations!

In [168]:
print(arr20/arr21)

[0.2        0.33333333 0.42857143 0.5       ]


In [169]:
print(arr20*arr21)

[ 5 12 21 32]


In [172]:
arr22= np.array([1,2,34,23,54,3,4,343,435,4,535,345,33,22])
total = arr22.sum()

In [173]:
total

1838

In [175]:
total2 = np.sum(arr22)

In [176]:
total2

1838

In [177]:
#Mean
mean= arr22.mean()

In [178]:
mean

131.28571428571428

In [186]:
sort = np.sort(arr22)

In [187]:
print(sort)

[  1   2   3   4   4  22  23  33  34  54 343 345 435 535]


In [188]:
decending = np.sort(arr22)[::-1]

In [189]:
decending

array([535, 435, 345, 343,  54,  34,  33,  23,  22,   4,   4,   3,   2,
         1])

In [198]:
median = np.median(arr22)

In [200]:
median

28.0

In [204]:
#flatten = it'll flat any array like a 3d array to 1d array immidiately

In [213]:
arr30= np.array(
    [
        [[1,2,3],[4,5,6]],
    [[178,98,87],[99,98,97]]
    ]
)


In [214]:
flat = arr30.flatten()

In [215]:
flat

array([  1,   2,   3,   4,   5,   6, 178,  98,  87,  99,  98,  97])