In [1]:
#1) to create 3X3 matrix using numpy with random numbers in the range of 1-100
"""

Matrix Operation Scaler operation
add 2
substract 3
divide 4
multiply 2
"""

'\n\nMatrix Operation Scaler operation\nadd 2\nsubstract 3\ndivide 4\nmultiply 2\n'

In [2]:
import numpy as np
matrix = np.random.randint(1,101,size=(3,3))
matrix

array([[ 6, 83, 28],
       [91, 59, 36],
       [86, 76, 30]])

In [3]:
matrix_add = matrix + 2
matrix_add

array([[ 8, 85, 30],
       [93, 61, 38],
       [88, 78, 32]])

In [4]:
matrix_sub = matrix -2
matrix_sub

array([[ 4, 81, 26],
       [89, 57, 34],
       [84, 74, 28]])

In [5]:
matrix_div = matrix/4
matrix_div

array([[ 1.5 , 20.75,  7.  ],
       [22.75, 14.75,  9.  ],
       [21.5 , 19.  ,  7.5 ]])

In [6]:
matrix_mult = matrix*2
matrix_mult

array([[ 12, 166,  56],
       [182, 118,  72],
       [172, 152,  60]])

In [7]:
#2) to create 4x4 matrix using numpy with random numbers in the range of 1-100 and print all odd numbers by loopinh
matrix2 = np.random.randint(1,101,size=(4,4))
matrix2

array([[73,  6,  8, 77],
       [47, 84, 88, 22],
       [57, 97, 38, 88],
       [44, 69, 56, 69]])

In [8]:
for i in matrix2:
    print('\n')
    print(i)#it'll print 1d array
    for j in i:
        if j!=0:
            print('Odd numbers in this row are :', j)




[73  6  8 77]
Odd numbers in this row are : 73
Odd numbers in this row are : 6
Odd numbers in this row are : 8
Odd numbers in this row are : 77


[47 84 88 22]
Odd numbers in this row are : 47
Odd numbers in this row are : 84
Odd numbers in this row are : 88
Odd numbers in this row are : 22


[57 97 38 88]
Odd numbers in this row are : 57
Odd numbers in this row are : 97
Odd numbers in this row are : 38
Odd numbers in this row are : 88


[44 69 56 69]
Odd numbers in this row are : 44
Odd numbers in this row are : 69
Odd numbers in this row are : 56
Odd numbers in this row are : 69


In [9]:
#2) to create 4x4 matrix using numpy with random numbers in the range of 1-100 and print mean of each row
y = np.random.randint(1,101,size=(4,4))
y

array([[ 14,  86,  86,  13],
       [ 74,  54,  38,   5],
       [ 38,  14,  82,  81],
       [ 35,  12,  20, 100]])

In [10]:
for i in y:
    print('\n')
    print('The row2', i, 'mean is :',i.mean())
    



The row2 [14 86 86 13] mean is : 49.75


The row2 [74 54 38  5] mean is : 42.75


The row2 [38 14 82 81] mean is : 53.75


The row2 [ 35  12  20 100] mean is : 41.75


In [11]:
#3. Make 2x2 matrix - add them ,subtract them, multiply them and divide them

mat_1 = np.random.randint(1,50,size=(2,2))
mat_2 = np.random.randint(1,50,size=(2,2))
print(mat_1,'\n')
print(mat_2)
print('\n')
#add
print(np.add(mat_1,mat_2))

[[41  5]
 [46 14]] 

[[46 18]
 [ 2 42]]


[[87 23]
 [48 56]]


In [12]:
print(np.subtract(mat_1,mat_2))

[[ -5 -13]
 [ 44 -28]]


In [13]:
 print(mat_1*mat_2) #simple array multiplication

[[1886   90]
 [  92  588]]


In [14]:
print(mat_1 @ mat_2) #matrix multiplication / dot product

[[1896  948]
 [2144 1416]]


In [15]:
print(mat_1 / mat_2) #mat_2 becomes inverse first in the function

[[ 0.89130435  0.27777778]
 [23.          0.33333333]]


In [16]:
#4 prove for transpose of a matrix, if below statements are true or False

# (A')' = A
# K x A' = (KA)' # k is any constant value
# (A+B)' = A' + B'
# (AB)' = B'A'

In [17]:
a = np.random.randint(3,76,(2,2))
print(a)

[[60 13]
 [ 5 70]]


In [18]:
transpose = a.T
print(transpose)

[[60  5]
 [13 70]]


In [19]:
a.T.T

array([[60, 13],
       [ 5, 70]])

In [20]:
#1st condition is true

In [21]:
# K x A' = (KA)' # k is any constant value
k=8
k* transpose 

array([[480,  40],
       [104, 560]])

In [22]:
(k*a).T

array([[480,  40],
       [104, 560]])

In [23]:
#proved

In [24]:
# (A+B)' = A' + B'
b= np.random.randint(32,76,size=(2,2))
if np.array_equal((a + b).T, a.T + b.T):
    print('True')

True


In [25]:
# (AB)' = B'A'
if np.array_equal(((a@b).T), (b.T@a.T)):
    print('true')

true


In [26]:
#5. to create 4x4 matrix using numpy with random numbers in the range of 1-150 and print even of each row which is less than 69
p = np.random.randint(1,151,size=(4,4))
for i in p:
    print('\n')
    print('row:',i)
    for j in i:
        if j%2==0 and j<69:
          print('The even numbers are , which are less than 69:', j)
        else:
            print('N/A')



row: [10 43 71 89]
The even numbers are , which are less than 69: 10
N/A
N/A
N/A


row: [123  23  92  83]
N/A
N/A
N/A
N/A


row: [ 41 148   7 111]
N/A
N/A
N/A
N/A


row: [ 48 150 120  12]
The even numbers are , which are less than 69: 48
N/A
N/A
The even numbers are , which are less than 69: 12


In [27]:
#6. create a 1d numpy array with random int 1 to 50 - should be 10 and  using for loop - print all the number greater  than mean
arr= np.random.randint(1,51,size=10)
arr

array([10, 40,  9,  7,  9, 43, 37, 23, 13,  4])

In [28]:
for i in arr:
    if i>arr.mean():
      print(i)

40
43
37
23


In [29]:
arr.mean()

19.5

In [30]:
#7. Numpy array 15 random - bw 10-100
#find and print maxmum value in array using while loop
arr8= np.random.randint(10,101,size=15)
arr8

array([23, 61, 61, 48, 13, 47, 53, 89, 78, 96, 78, 11, 23, 19, 65])

In [34]:
max1 = arr8[0]
i=1
while i<len(arr8):
    if arr8[i]>max1:
        max1 = arr8[i]
    i+=1
print(max1)

96


In [40]:
i=5
while i>0:
    print(i*'*',)

    i-=2

*****
***
*


In [41]:
#a="aabcasaaabcassssbaa" create a dictionary where key is every unique character and value is the number
# of times each unique character is repeting
#eg {a:5,b:7.....}

In [44]:
char = 'aabcasaaabcassssbaa'
char_value ={}
for i in char:
    if i not in char_value:
        char_value[i]=1
    else:
        char_value[i]+=1
print(char_value)

{'a': 9, 'b': 3, 'c': 2, 's': 5}


In [52]:

# Create a string and store your name in it using userinput
# print the length of the string without using any inbuilt function

name = input('enter your name:')
length = 0
for i in name:
    length+=1
print(length)

enter your name: Nihal Singh


11
